### ISSUE TITLE
SSL support

### ISSUE THREAD

**Issue by zewelor** [synesthesiam/hassio-addons#1]
Hi

thanks for great addon. It works wonderful. Are you considering adding ssl support, so that web ui can be accessed using https and be used as iframe in ssl enabled HA ? Example addon supporting ssl setup: https://github.com/esphome/hassio/blob/master/esphome/config.json#L25

**Comment by synesthesiam** [comment]
Sure, I should be able to add this fairly easily. I'm using Flask for my webserver, and it looks like it supports adding a custom certificate or generating one of the fly.
