### ISSUE TITLE
Rhasspy 2.5 add-on, where is it?

### ISSUE THREAD

**Issue by basnijholt** [synesthesiam/hassio-addons#15]
I am excited to try v2.5, however, from the installation instructions at https://rhasspy.readthedocs.io/en/latest/installation/ it looks like the add-on way of installing isn't supported anymore. Is this correct? And if not, where is the add-on located?

edit: I see this PR https://github.com/synesthesiam/hassio-addons/pull/13

**Comment by synesthesiam** [comment]
https://github.com/synesthesiam/hassio-addons/tree/master/rhasspy25

**Comment by basnijholt** [comment]
Great! Has it been tested? Because from what I read on the forums @Romkabouter doesn't use this installation method.

I cannot get the audio to pass correctly (nor for the 2.4 add-on).

**Comment by Romkabouter** [comment]
I have developed and tested it as a local Addon, which should work similar as a non-local AddOn.
You might need to it the "Reload" button on the App Store in Home Assistant. Then the addon should popup under "Synesthesiam Hass.IO Add-Ons"

Keep in mind that this used the PRE-RELEASE, I am currently changing it to the correct release.

![image](https://user-images.githubusercontent.com/4774478/86892534-ad4eba00-c100-11ea-9cd6-73053cb7badf.png)

**Comment by basnijholt** [comment]
Thanks for your reply @Romkabouter. However, my question is not about how to install it, but whether you have tested the add-on using a microphone? AFAIK there are issues with passing through audio devices in Hass.io.

**Comment by Romkabouter** [comment]
Ah ok sorry, no I did not test that. This AddOn was quickly added for the pre-release so people could test it with HassIO.
I am using a MQTT audio input, but I will investigate a mic as well when I update this addon to the final rhasppy25 release.

**Comment by Romkabouter** [comment]
> I have developed and tested it as a local Addon, which should work similar as a non-local AddOn.
> You might need to it the "Reload" button on the App Store in Home Assistant. Then the addon should popup under "Synesthesiam Hass.IO Add-Ons"
> 
> Keep in mind that this used the PRE-RELEASE, I am currently changing it to the correct release.
> 
> ![image](https://user-images.githubusercontent.com/4774478/86892534-ad4eba00-c100-11ea-9cd6-73053cb7badf.png)
> 
> I am going to install it from the repo as well to check if everthing works.

The addon actually using the latest already, so Google Wavenet can be used
