### ISSUE TITLE
Problem with hassio repo

### ISSUE THREAD

**Issue by zewelor** [synesthesiam/hassio-addons#2]
Hi

I've got problem with this repo. It gets deleted, and in hass logs I can see:
```
19-03-06 19:18:46 INFO (MainThread) [hassio.addons.git] Clone add-on https://github.com/synesthesiam repository
19-03-06 19:18:47 ERROR (MainThread) [hassio.addons.git] Can't clone https://github.com/synesthesiam repository: Cmd('git') failed due to: exit code(128)
  cmdline: git clone --depth=1 --recursive --shallow-submodules -v https://github.com/synesthesiam /data/addons/git/01d82e91
  stderr: 'Cloning into '/data/addons/git/01d82e91'...
remote: Not Found
fatal: repository 'https://github.com/synesthesiam/' not found
'.
19-03-06 19:18:47 ERROR (MainThread) [hassio.addons] Can't load from repository https://github.com/synesthesiam
```

I'm not sure but maybe problem is with wrong url in repository.json file ?
https://github.com/synesthesiam/hassio-addons/blob/master/repository.json

Maybe url key should be "https://github.com/synesthesiam/hassio-addons/" ?

**Comment by synesthesiam** [comment]
OK, I changed the URL key. Did this fix it for you?

Also, I apologize for not seeing this issue earlier. I wasn't receiving notifications from Github.
