### ISSUE TITLE
Web UI cannot be added to sidebar

### ISSUE THREAD

**Issue by thetic** [synesthesiam/hassio-addons#23]
This is a fairly typical option for add-ons (eg. ESPHome, Node Red).

**Comment by synesthesiam** [comment]
Can you give some more detail on this? I'm not familiar.

**Comment by thetic** [comment]
Most add-ons with web UIs expose them through Home Assistant's UI with a toggle like seen in this image: https://www.elektormagazine.com/assets/upload/img/public/original/200019-007-94-original-esphome-in-home-assistant.png

**Comment by thetic** [comment]
BTW, should I be using this repo or https://github.com/rhasspy/hassio-addons?

**Comment by thetic** [comment]
https://developers.home-assistant.io/docs/add-ons/presentation/#ingress

**Comment by Nailik** [comment]
> BTW, should I be using this repo or https://github.com/rhasspy/hassio-addons?

do you have an answer for that? 
Also because https://github.com/rhasspy/hassio-addons/issues/5 is still open, how can i access the rhasspy web ui?
