### ISSUE TITLE
Setting up HASSIO as external MQTT server

### ISSUE THREAD

**Issue by MikeLDPT** [synesthesiam/hassio-addons#24]
Hi,
I attempted to configure an external MQTT server for Rhasspy and as Rhasspy was installed under HASSIO on a Raspberry Pi, Ichose to use the one within Hassio. I find that I am getting MQTT issues occuring:

![image](https://user-images.githubusercontent.com/70011875/105641992-d8bbab00-5e7e-11eb-80c5-7ace440c47c9.png)

As you can see it turned up 164 times in a matter of seconds. It is the WAV files I believe (and each is quite large) and I tried to research how to stop this. I found that the best advice was to use UDP settings for both Audio Input and Wake Word.  I set the port to 12202.  In Audio Input (using the recommended pyaudio) I have tried leaving the preceding entry to the 'port' pre-poulated by 'host' as it is, and also as 'homeassistant'.  The result is still the WAV file errors appearing in the HA log file.  I have also tried using 'localhost' in place of the default of 'host', but then no notice seems to be taken of any intents I try to give. Apparantly the result of using UDP is meant to be that no WAV files will be posted to the MQQT queues until the Wake Word has been matched.  It takes about 5 attempts to match the wake word so 164 entries seems a little extreme. 

Are you aware of this and can you please suggest a solution to avoid so many WAV files being posted to the HA MQTT?

Many thanks.

**Comment by synesthesiam** [comment]
The Hermes protocol passes WAV chunks through MQTT on the `hermes/audioServer/<siteId>/audioFrame` topic. HA should be configured to not listen to this topic.

**Comment by MikeLDPT** [comment]
Thanks Synesthesiam, I will attempt to find out how to do that.
