### ISSUE TITLE
Access token is not filled in Hassio

### ISSUE THREAD

**Issue by frkos** [synesthesiam/hassio-addons#4]
Hello, I'm using Hass.io addon and I found that to make a connection to Home Assistant I need to generate Long Lived access token manually
According to description it should be filled automatically, but it's not

If i provide correct link to Home Assistant and token all works with no issues

**Comment by synesthesiam** [comment]
It's looking like they must have changed the Hass.io token header to X-HASSIO-KEY at some point? I'll make the change in Rhasspy and see if that fixes it.

**Comment by Romkabouter** [comment]
I have read this: https://developers.home-assistant.io/docs/en/hassio_addon_communication.html#hassio-api

The page says: hassio_api, but in the config.json is that homeassistant_api
I have not tried it locally, but that might be the issue

**Comment by Romkabouter** [comment]
I think this one can be closed, it is fixed with version 2.4.15.2
