### ISSUE TITLE
Using Precise for wake word detection fails with "No module named 'precise_runner'"

### ISSUE THREAD

**Issue by OpinionatedGeek** [synesthesiam/hassio-addons#5]
Hi,

I'm new to all this but I'm having difficulty getting Mycroft Precise wake word detection working.

I created my custom wake word files on a different machine. Is there a particular source release/version of Mycroft Precise I should use so the .venvs match? I just used HEAD but I don't know if that will cause problems later.

I copied the relevant files across to my hassio Pi and edited the `profile.json`. My (redacted) `profile.json` is:
```
{
    "handle": {
        "system": "hass"
    },
    "home_assistant": {
        "access_token": "redacted",
        "url": "redacted"
    },
    "microphone": {
        "arecord": {
            "device": "speaker"
        },
        "system": "arecord"
    },
    "wake": {
        "system": "precise",
        "precise": {
            "model": "redacted.pb",
            "sensitivity": 0.5,
            "trigger_level": 3,
            "chunk_size": 2048
        }
    },
    "rhasspy": {
        "listen_on_start": true
    }
}
```

When I try to start rhasspy it can't find the 'precise_runner' library. Here's the exact error:
```
Traceback (most recent call last):
  File "/usr/share/rhasspy/rhasspy/actor.py", line 159, in on_receive
    self.transition("started")
  File "/usr/share/rhasspy/rhasspy/actor.py", line 230, in transition
    getattr(self, transition_method)(from_state)
  File "/usr/share/rhasspy/rhasspy/dialogue.py", line 265, in to_started
    self.transition("loading")
  File "/usr/share/rhasspy/rhasspy/actor.py", line 230, in transition
    getattr(self, transition_method)(from_state)
  File "/usr/share/rhasspy/rhasspy/dialogue.py", line 301, in to_loading
    self.load_actors()
  File "/usr/share/rhasspy/rhasspy/dialogue.py", line 825, in load_actors
    self._wake = self.createActor(self.wake_class)
  File "/usr/share/rhasspy/rhasspy/actor.py", line 188, in createActor
    child_actor = cls().start()
  File "/usr/share/rhasspy/rhasspy/wake.py", line 511, in __init__
    from precise_runner import ReadWriteStream
ModuleNotFoundError: No module named 'precise_runner'
```
`precise-runner` seems to be a part of the `mycroft-precise` project, so maybe it's not included any more?

Then I saw this repository had a 'mycroft-precise' add-on, so I tried installing that. It fails to install with the error:
```
    20-01-05 14:41:45 ERROR (SyncWorker_3) [hassio.docker.addon] Can't build 75f2ff60/armv7-addon-precise-rhasspy:0.2.0-4: The command '/bin/sh -c pip3 install --no-cache-dir tensorflow==1.8.0' returned a non-zero code: 1
```

The 'mycroft-precise' add-on may be old - the last update for it was 9 months ago. I'm not sure if that's the approach I should be taking or not.

I'm not sure which of those two approaches is the right one to take, so I'm not sure what my next steps should be in trying to debug this. Which is the best way to try to get Precise wake words working?

Many thanks.

**Comment by synesthesiam** [comment]
I've tried to build Precise back into the main Docker image. Please test with 2.4.20 and see if it works out of the box now.
