### ISSUE TITLE
Build of Mycroft-Precise for Rhasspy fails

### ISSUE THREAD

**Issue by docholiday** [synesthesiam/hassio-addons#9]
Hi there, I'm trying to install mycroft-prcecise for Rhasspy.
The build fails however:

> 20-03-11 01:02:32 INFO (MainThread) [supervisor.addons] Create Home Assistant add-on data folder /data/addons/data/75f2ff60_precise-rhasspy
20-03-11 01:02:32 INFO (SyncWorker_13) [supervisor.docker.addon] Start build 75f2ff60/armv7-addon-precise-rhasspy:0.2.0-4
20-03-11 01:14:39 ERROR (SyncWorker_13) [supervisor.docker.addon] Can't build 75f2ff60/armv7-addon-precise-rhasspy:0.2.0-4: The command '/bin/sh -c pip3 install --no-cache-dir tensorflow==1.8.0' returned a non-zero code: 1

My system:
Hassio on Raspberry Pi 3B
HassOS 3.12
Home Assistant 0.106.6
Supervisor 209

Any idea how to fix this?

**Comment by docholiday** [comment]
Update: I tried to run the docker container on my PC -> cloned your repo, built the docker file.
Container is built successfully, however in the run.sh it says
`CONFIG_PATH="/data/options.json"`
which doesn't seem to be available:
`jq: error: Could not open file /data/options.json: No such file or directory`

**Comment by synesthesiam** [comment]
I've tried to build Precise back into the main Docker image. Please test with 2.4.20 and see if it works out of the box now.

**Comment by Romkabouter** [comment]
I have a PR open to remove the mycroft addon.

It is build into 2.4 and 2.5. Please inform us if we can close this issue @docholiday
